### ISSUE TITLE
Loving, missing feature.

### ISSUE THREAD

**Issue by Chris2011** [ldawkes/LiveBeans#1]
Hey, I saw your repo and I'm willing to test it. Hopefully, it will work as this atom plugin here: http://blog.pusher.com/atom-pair/. I stay tuned :) :+1: If there is a alpha or beta state, please release it here with an nbm file.

Cheers

Chris

**Comment by ldawkes** [comment]
Hey there Chris,

Yeah, that's sort of the style i'm aiming to have with this plugin, I'm still relatively new to Java, so bear with me on this! I'm hoping to have something basic akin to the Atom plugin you mentioned sometime in the next couple of weeks.

Luke Dawkes.

**Comment by Chris2011** [comment]
Great to here, will test it, if it's possible :) maybe then I can help or so.

**Comment by ldawkes** [comment]
Any help you may want to offer is welcome, in any form!

**Comment by Chris2011** [comment]
Give me a hint here, if the plugin is in a good stage to test it with friends or with you :)

**Comment by ldawkes** [comment]
Hi yeah, sorry, just been bogged down with uni work recently, hoping to get the project back on track soon, and actually to a working degree!

**Comment by Chris2011** [comment]
Hey, is the plugin in a working state to test it?

**Comment by Chris2011** [comment]
Any news here?

**Comment by Chris2011** [comment]
I tested it out, seems working fine, with 2 little bugs. Hope that you can fix it soon :) Would love to use it for pair programming.

**Comment by Chris2011** [comment]
Smth new here?

**Comment by ldawkes** [comment]
Sorry, haven't really worked on this for a year now, I probably won't be continuing this project for a while, at least not until my personal life is all organised and sorted out. Sorry.
